
abstract=
ontologyTitle=Deutsche Digitale Bibliothek Europeana Data Model
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=ddb
ontologyName=Deutsche Digitale Bibliothek Europeana Data Model
thisVersionURI=https://ise-fizkarlsruhe.github.io/ddbkg/ddbedm/source/ddbedm-full.owl
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=2026-03-09
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=https://creativecommons.org/licenses/by/4.0/
licenseIconURL=null
citeAs= Deutsche Digitale Bibliothek Europeana Data Model. Revision: 2026-03-09. Retrieved from: https://ise-fizkarlsruhe.github.io/ddbkg/ddbedm/source/ddbedm-full.owl
DOI=
status=Ontology Specification Draft
logo=
description=The DDB-EDM is an extension of the implemented the Europeana Mapping Guidelines  described in 2013. Implementation details are presented at the International Conference  on Dublin Core and Metadata Applications in 2014 (Rühle et al., 2014).  See https://dcpapers-data.dublincore.org/articles/dc-2014/952136503/files/dcmi-952136503.pdf
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=Stefanie Rühle;Francesca Schulze;Michael Büchner
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
