
abstract=***MOCHO***, or **M**iddle **O**ntology for Cross-domain **C**ultural **H**eritage **O**bjects, is a reusable alignment layer between the Europeana Data Model (EDM) [1] and GLAM-spanning domain ontologies. MOCHO defines WEMI-typed entities and four alignment patterns. WEMI stands for Work, Expression, Manifestation, Item, and is a conceptual model that first appeared in FRBR for describing bibliographic resources [2].
ontologyTitle=Middle Ontology for Cultural Heritage Objects (MOCHO)
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=https://ise-fizkarlsruhe.github.io/ddbkg/mocho/source/mocho-full.owl
ontologyName=Middle Ontology for Cultural Heritage Objects (MOCHO)
thisVersionURI=https://ise-fizkarlsruhe.github.io/ddbkg/mocho/source/mocho-full.owl
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=2026-03-10
licenseURI=https://creativecommons.org/licenses/by/4.0/deed.en
licenseName=https://creativecommons.org/licenses/by/4.0/deed.en
licenseIconURL=null
citeAs= Middle Ontology for Cultural Heritage Objects (MOCHO). Revision: 2026-03-10.
DOI=
status=Ontology Specification Draft
logo=
description=MOCHO, or Mid-Level Ontology for Cross-domain Cultural Heritage Objects, is a reusable alignment layer between the Europeana Data Model (EDM) and GLAM-spanning domain ontologies. MOCHO defines WEMI-typed entities and four alignment patterns.

introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Mary Ann Tan
authorsURI=;;
authorsInstitution=FIZ Karlsruhe;Karlsruhe Institute of Technology
authorsInstitutionURI=;;
contributors=Genet Asefa Gesese;Harald Sack
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
